DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE `usuarios` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `slots_pj` INT(11) NOT NULL DEFAULT 3,
    `usuario` VARCHAR(50) NOT NULL,
    `contrasena` VARCHAR(60) NOT NULL,
    `correo` VARCHAR(150) NOT NULL,
    `fechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ultimoActivo` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `socialClub` VARCHAR(20) NOT NULL,
    `socialClubId` VARCHAR(255) NOT NULL,
    `ip` VARCHAR(85) NOT NULL,
    `ip_registro` VARCHAR(85) NOT NULL,
    `pin_seguridad` VARCHAR(10) NOT NULL,
    `cef_chat_preferencia` INT(1) NOT NULL
);

DROP TABLE IF EXISTS `personajes`;
CREATE TABLE `personajes` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `idusuario` INT(11) NOT NULL,
    `n_pj` INT(11) NOT NULL,
    `nombre` VARCHAR(60) NOT NULL,
    `sex` INT(11) NOT NULL,
    `vida` INT(11) NOT NULL DEFAULT 100,
    `armadura` INT(11) NOT NULL DEFAULT 0,
    `numero_tlf` VARCHAR(11) NOT NULL,
    `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `facciones` VARCHAR(255),
    `faccion_principal` INT(11) NOT NULL,
    `rangos_facciones` VARCHAR(255),
    `rango_principal` INT(11) NOT NULL,
    `dinero` VARCHAR(255) NOT NULL DEFAULT '0',
    `banco` VARCHAR(255) NOT NULL DEFAULT '0',
    `pay` VARCHAR(255) NOT NULL DEFAULT '0',
    `ultima_conexion` DATETIME NOT NULL,
    `ultima_ip` VARCHAR(40) NOT NULL,
    `online` INT(1) NOT NULL DEFAULT 0,
    `mama` INT(11) NOT NULL,
    `papa` INT(11) NOT NULL,
    `mezcla_padres` FLOAT NOT NULL DEFAULT 0.5,
    `mezcla_piel` FLOAT NOT NULL DEFAULT 0.5,
    `piel_mama` INT(11) DEFAULT NULL,
    `piel_papa` INT(11) DEFAULT NULL,
    `color_ojos` INT(11) NOT NULL,
    `pelo` INT(11) NOT NULL,
    `color_pelo` INT(11) NOT NULL,
    `color_sec_pelo` INT(11) NOT NULL,
    `barba` INT(11) NOT NULL,
    `color_barba` INT(11) NOT NULL,
    `caracteristicas_cara` VARCHAR(255),
    `manchas` VARCHAR(255),
    `vello_facial` VARCHAR(255),
    `cejas` VARCHAR(255),
    `envejecimiento` VARCHAR(255),
    `constituir` VARCHAR(255),
    `rubor` VARCHAR(255),
    `tez` VARCHAR(255),
    `dano_del_sol` VARCHAR(255),
    `lapiz_labial` VARCHAR(255),
    `lunarespecas` VARCHAR(255),
    `pelo_pecho` VARCHAR(255),
    `manchas_corporales` VARCHAR(255),
    `int_manchas_corporales` INT(11) NOT NULL DEFAULT 0,
    `posicion` VARCHAR(255),
    `rotacion` VARCHAR(255),
    `dimension` FLOAT NOT NULL
);